name: Backend CI

on: [push]

env:
  JAR_NAME: thesis-app

jobs:
  # Compiles the project, runs the tests and creates a runnable jar file
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Test and build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Upload the built jar file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.JAR_NAME }}
          path: build/libs/thesis-*-SNAPSHOT.jar
          retention-days: 1

  # Dummy deployment job
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download the jar file
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.JAR_NAME }}
      - name: Deploy
        run: ls -lh
